easy_admin:
  design:
    brand_color: '#1ABC9C'
    menu:
      - { label: 'Users' }
      - { entity: 'Users', css_class: 'default', icon: 'user' }
      - { entity: 'Skills', css_class: 'default', icon: 'book' }
      - { label: 'Teams' }
      - { entity: 'Teams', css_class: 'default', icon: 'group' }
      - { entity: 'Teamtasks', css_class: 'default', icon: 'group' }
      - { label: 'Admin' }
      - { entity: 'Teampoints', css_class: 'default', icon: 'group' }
      - { entity: 'Skill', css_class: 'default', label: 'Skill List', icon: 'cogs' }
      - { label: 'Project' }
      - { entity: 'Projects', css_class: 'default', icon: 'code-branch' }
      - { entity: 'Projectdetails', css_class: 'default', icon: 'code-branch' }
